/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.home;

import com.databaseCon.MotorPH_DB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class MotorPH_LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form MotorPH_LoginFrame
     */
    public MotorPH_LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1Login = new javax.swing.JButton();
        jButton1ForgetPass = new javax.swing.JButton();
        jButton2ChangePass = new javax.swing.JButton();
        jPasswordField1Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 100));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MO-IT101 - Computer Programming 1");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Section : A1101");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group 1");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1024, 100));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 560, 340));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel10.setText("Welcome!");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, -1));

        jTextField1Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1EmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1EmailKeyTyped(evt);
            }
        });
        jPanel4.add(jTextField1Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Password:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Email:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jButton1Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1Login.setText("Login");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jButton1ForgetPass.setBackground(new java.awt.Color(153, 153, 153));
        jButton1ForgetPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1ForgetPass.setForeground(new java.awt.Color(255, 255, 255));
        jButton1ForgetPass.setText("Forget Password");
        jButton1ForgetPass.setBorderPainted(false);
        jButton1ForgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ForgetPassActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1ForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        jButton2ChangePass.setBackground(new java.awt.Color(153, 153, 153));
        jButton2ChangePass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2ChangePass.setForeground(new java.awt.Color(255, 255, 255));
        jButton2ChangePass.setText("Change Password");
        jButton2ChangePass.setBorderPainted(false);
        jButton2ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ChangePassActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2ChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 290, 140, -1));
        jPanel4.add(jPasswordField1Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 230, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 340, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
        
       String email = jTextField1Email.getText();
        String password = jPasswordField1Password.getText();
        
        if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Email and/or password fields are empty.");
        return; // Exit the method without proceeding further
    }
        Bal balObj = new Bal();
       boolean b = false;
        
   
        try {
            
            String query = "select ID, `Last Name`, `First Name`, Birthday, Email, Password, Designation, FirstLogin from motorphdb where Email = '"+email+"' AND Password = '"+password+"'";
            Statement st = MotorPH_DB.con.createStatement();
            ResultSet rs = st.executeQuery(query);
           
            if (rs.next()){
                b = true;
                   String designation = rs.getString("Designation");
                    int firstLoginValue = rs.getInt("FirstLogin");
                    
            if (firstLoginValue == 1) {
                // Navigate to ChangePass1stLoginFrame
                if (designation.equals("Admin")) {
                int id = rs.getInt(1);
                    String firstName =rs.getString(3);
                String lastName =rs.getString(2);
                Date birthday = rs.getDate(4);
                email =rs.getString(5);
                Bal.AdID = id;
                Bal.AdFirstName = firstName;
                Bal.AdLastName = lastName;
                Bal.AdBirthday = (java.sql.Date) birthday;
                Bal.AdEmail = email;
                
                 MotorPH_HomeJFrame adminObj = new MotorPH_HomeJFrame();
                
                 adminObj.show();
                this.hide();
            } else if (designation.equals("Employee")) {
                    int id = rs.getInt(1);
                    String firstName =rs.getString(3);
                String lastName =rs.getString(2);
                Date birthday = rs.getDate(4);
                email =rs.getString(5);
                Bal.EmpID = id;
                Bal.EmpFirstName = firstName;
                Bal.EmpLastName = lastName;
                Bal.EmpBirthday = (java.sql.Date) birthday;
                Bal.EmpEmail = email;
                
                MotorPH_EmpFrame empObj = new MotorPH_EmpFrame();
                empObj.show();
                this.hide();
            } 
                
                ChangePass1stLoginFrame changePassFrame = new ChangePass1stLoginFrame();
                changePassFrame.setVisible(true);
                this.dispose(); // Close current login frame
            } else if (designation.equals("Admin")) {
                int id = rs.getInt(1);
                    String firstName =rs.getString(3);
                String lastName =rs.getString(2);
                Date birthday = rs.getDate(4);
                email =rs.getString(5);
                Bal.AdID = id;
                Bal.AdFirstName = firstName;
                Bal.AdLastName = lastName;
                Bal.AdBirthday = (java.sql.Date) birthday;
                Bal.AdEmail = email;
                
                 MotorPH_HomeJFrame adminObj = new MotorPH_HomeJFrame();
                
                 adminObj.show();
                this.hide();
            } else if (designation.equals("Employee")) {
                    int id = rs.getInt(1);
                    String firstName =rs.getString(3);
                String lastName =rs.getString(2);
                Date birthday = rs.getDate(4);
                email =rs.getString(5);
                Bal.EmpID = id;
                Bal.EmpFirstName = firstName;
                Bal.EmpLastName = lastName;
                Bal.EmpBirthday = (java.sql.Date) birthday;
                Bal.EmpEmail = email;
                
                MotorPH_EmpFrame empObj = new MotorPH_EmpFrame();
                empObj.show();
                this.hide();
            } 
            
            JOptionPane.showMessageDialog(null, "Login Successfully!");
            }else {
                
                JOptionPane.showMessageDialog(null, "Invalid Email and Password try again.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ""+e);
        }
             
    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jButton1ForgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ForgetPassActionPerformed
         this.hide();
        ForgetPass loginObj = new ForgetPass();
        loginObj.show();
    }//GEN-LAST:event_jButton1ForgetPassActionPerformed

    private void jButton2ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ChangePassActionPerformed
         this.hide();
        ChangePassFrame loginObj = new ChangePassFrame();
        loginObj.show();
    }//GEN-LAST:event_jButton2ChangePassActionPerformed

    private void jTextField1EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1EmailKeyReleased
    
    
    }//GEN-LAST:event_jTextField1EmailKeyReleased

    private void jTextField1EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1EmailKeyTyped
         
    }//GEN-LAST:event_jTextField1EmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotorPH_LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ForgetPass;
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton2ChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1Password;
    private javax.swing.JTextField jTextField1Email;
    // End of variables declaration//GEN-END:variables
}
